const COMMON_WORDS = [
  'a', 'about', 'above', 'across', 'act', 'add', 'after', 'again', 'age', 'ago', 'air', 'all', 'also',
  'always', 'am', 'among', 'an', 'and', 'another', 'answer', 'any', 'anyone', 'anything', 'appear', 'are',
  'area', 'around', 'as', 'ask', 'at', 'away', 'back', 'bad', 'ball', 'bank', 'base', 'be', 'bear', 'beat',
  'beautiful', 'became', 'because', 'become', 'been', 'before', 'began', 'begin', 'behind', 'being', 'best',
  'better', 'between', 'big', 'bird', 'black', 'blue', 'boat', 'body', 'book', 'both', 'box', 'boy', 'bring',
  'brother', 'build', 'built', 'but', 'buy', 'by', 'call', 'came', 'can', 'car', 'care', 'carry', 'case',
  'cat', 'cause', 'change', 'check', 'child', 'children', 'city', 'class', 'clear', 'close', 'cold', 'come',
  'common', 'company', 'could', 'country', 'course', 'cut', 'dark', 'day', 'decide', 'did', 'die', 'different',
  'do', 'does', 'dog', 'done', 'door', 'down', 'draw', 'dream', 'drive', 'dry', 'during', 'each', 'early',
  'earth', 'easy', 'eat', 'end', 'enough', 'even', 'ever', 'every', 'example', 'eye', 'face', 'fact', 'fall',
  'family', 'far', 'fast', 'father', 'feel', 'feet', 'few', 'field', 'find', 'fine', 'fire', 'first', 'fish',
  'five', 'follow', 'food', 'for', 'form', 'found', 'four', 'free', 'friend', 'from', 'front', 'full', 'game',
  'gave', 'get', 'girl', 'give', 'go', 'gone', 'good', 'got', 'great', 'green', 'ground', 'group', 'grow',
  'had', 'half', 'hand', 'hard', 'has', 'have', 'he', 'head', 'hear', 'heard', 'help', 'her', 'here', 'high',
  'him', 'his', 'hold', 'home', 'horse', 'hot', 'hour', 'house', 'how', 'idea', 'if', 'important', 'in', 'into',
  'is', 'it', 'its', 'job', 'just', 'keep', 'kind', 'king', 'knew', 'know', 'land', 'large', 'last', 'late',
  'later', 'laugh', 'law', 'lay', 'lead', 'learn', 'leave', 'left', 'less', 'let', 'letter', 'life', 'light',
  'like', 'line', 'little', 'live', 'long', 'look', 'lot', 'love', 'low', 'made', 'make', 'man', 'many', 'map',
  'mark', 'may', 'mean', 'men', 'might', 'mile', 'mind', 'mine', 'miss', 'money', 'month', 'more', 'most', 'mother',
  'mountain', 'move', 'much', 'music', 'must', 'my', 'name', 'near', 'need', 'never', 'new', 'next', 'night',
  'no', 'not', 'note', 'nothing', 'now', 'number', 'of', 'off', 'often', 'oil', 'old', 'on', 'once', 'one',
  'only', 'open', 'or', 'order', 'other', 'our', 'out', 'over', 'own', 'paper', 'part', 'pass', 'people', 'place',
  'plan', 'play', 'point', 'power', 'problem', 'put', 'question', 'quick', 'rain', 'ran', 'rather', 'read', 'real',
  'red', 'right', 'river', 'road', 'rock', 'room', 'run', 'said', 'same', 'saw', 'say', 'school', 'sea', 'second',
  'see', 'seem', 'self', 'set', 'seven', 'several', 'she', 'ship', 'short', 'should', 'show', 'side', 'since',
  'sing', 'sit', 'six', 'sky', 'small', 'so', 'some', 'song', 'soon', 'sound', 'south', 'space', 'speak', 'spell',
  'stand', 'start', 'state', 'stay', 'step', 'still', 'stop', 'story', 'street', 'strong', 'study', 'such', 'sun',
  'system', 'take', 'talk', 'teach', 'tell', 'ten', 'than', 'that', 'the', 'their', 'them', 'then', 'there', 'these',
  'they', 'thing', 'think', 'this', 'those', 'thought', 'three', 'through', 'time', 'together', 'told', 'too', 'took',
  'town', 'tree', 'true', 'try', 'turn', 'two', 'under', 'until', 'up', 'us', 'use', 'usual', 'very', 'voice', 'walk',
  'want', 'war', 'was', 'water', 'way', 'we', 'well', 'went', 'were', 'what', 'when', 'where', 'which', 'while',
  'white', 'who', 'why', 'will', 'with', 'without', 'woman', 'word', 'work', 'world', 'would', 'write', 'year', 'yes',
  'yet', 'you', 'young', 'your', 'zero',
  'dot', 'got', 'shot', 'spot', 'lot', 'not', 'hot', 'pot', 'cot', 'plot',
  'rhyme', 'prime', 'dime', 'time', 'line', 'mine', 'fine', 'shine', 'tone', 'alone', 'stone', 'phone',
  'day', 'night', 'light', 'bright', 'right', 'fight', 'might', 'tight',
]

export const COMMON_ENGLISH = new Set(COMMON_WORDS)

export const isCommonEnglishWord = (word: string) => COMMON_ENGLISH.has(word)
